- name: Install Nginx
  yum:
    name: nginx
    state: present

- name: Configure Nginx as reverse proxy
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf

- name: Enable and restart Nginx
  service:
    name: nginx
    state: restarted
    enabled: true
