- name: Ensure SELinux is disabled
  ansible.posix.selinux:
    state: disabled

- name: Disable and stop firewalld
  service:
    name: firewalld
    state: stopped
    enabled: false

- name: Install chrony
  yum:
    name: chrony
    state: present

- name: Enable and start chronyd
  service:
    name: chronyd
    state: started
    enabled: true

- name: Add Docker repository
  yum_repository:
    name: docker-ce
    description: Docker CE Repository
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo

- name: Install Docker packages
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    allowerasing: true

- name: Enable and start Docker service
  service:
    name: docker
    state: started
    enabled: true
